version: "3.5"

services:
  backend:
    image: exer12back
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/mydir/logs.txt
    environment:
      - REDIS=redis
      - DB_HOST=db
      - DB_USERNAME=back
      - DB_PASSWORD=end

  frontend:
    image: exer12front
    build: ../frontend-example-docker/
    ports:
      - 5000:5000

  redis:
    image: redis

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=back
      - POSTGRES_PASSWORD=end
